### ISSUE TITLE
Cannot find module solc\soljson

### ISSUE THREAD

**Issue by chicket** [tronprotocol/tronbox#100]
I installed TronBox on my windows system using
`npm install -g tronbox`

Project was init successfully using
`tronbox init`

But the compile commands like these are failing
```
tronbox compile
tronbox migrate
```

This is the error I'm getting:

![Capture](https://user-images.githubusercontent.com/75201832/110682218-b39db480-8200-11eb-9740-f25ba07d3588.PNG)

**Comment by llwslc** [comment]
Can you find the soljson_v0.4.25 in .tronbox?

**Comment by chicket** [comment]
Never worked for me on Windows.
Works fine on Ubuntu

**Comment by folowing** [comment]
may be you should try to run `tronbox --download-compiler 0.4.25` again then rerun `tronbox compile`.

**Comment by ericobi** [comment]
https://developers.tron.network/reference/tronbox-configuration#resolve-naming-conflicts-on-windows

You should do this. @chicket
