### ISSUE TITLE
Use another account for calls in a test

### ISSUE THREAD

**Issue by asinyagin** [tronprotocol/tronbox#115]
Hi,

How can I change a sender of contract call in my tests?

Like `from:` field in Truffle.
```
await contract.someMethod(arg1, arg2, {
  from: myAccount,
});
```

There's a method `tronWeb.setAddress()`. Looks like it should change the sender, but it doesn't do that in my tests.

Thank you!

**Comment by llwslc** [comment]
Please try the below code. 


```js
const TestContract = artifacts.require("./TestContract.sol");
const TronWeb = require('tronweb')


TestContract.deployed().then(t => {
  t.myBalance().then(console.log)

  const _tronWeb = new TronWeb({
    fullHost:  tronWeb.fullNode.host,
    privateKey: '01'
  })

  _tronWeb.setAddress('TXYZopYRdj2D9XRtbG411XZZ3kM5VkAeBf')
  _tronWeb.contract().at(t.address)
  .then(contract => {
    contract.myBalance().call().then(console.log())
  })
});
```

```solidity
// SPDX-License-Identifier: MIT
pragma solidity >=0.4.23 <=0.8.0;

contract TestContract {
  function myBalance() public view returns (uint) {
    return address(msg.sender).balance;
  }
}
```

**Comment by rubo** [comment]
While the workaround above works, it's a very inconvenient solution. Having `{from: account}` working for `.call()` and `.send()` is much more convenient and is the way it should be. This is a big headache and a major problem that needs to be addressed I believe.
