### ISSUE TITLE
How to call a contract method with a struct parameter

### ISSUE THREAD

**Issue by asinyagin** [tronprotocol/tronbox#118]
I have the solidity method:
```solidity
struct TestS {
    uint a;
    uint b;
}
...
function test(TestS memory s) external {
}
```

I tried to call it with the following code:
```javascript
await contract.test({a: 1, b: 2});
```
But I get an error: `Uncaught Error: Invalid argument count provided`

How to call such a method correctly?

Thank you!

**Comment by llwslc** [comment]
Sorry, Tronbox does not support ABIEncoderV2. We will support it as soon as possible.

**Comment by llwslc** [comment]
Please try the below code

```solidity
struct TestS {
    uint a;
    uint b;
}

function test(uint a, uint b) external {
    TestS memory s = TestS(a, b);
}
```
