### ISSUE TITLE
Test command is not taking the solc version from tronbox.js

### ISSUE THREAD

**Issue by GalinDinkov** [tronprotocol/tronbox#119]
### Problem:
If the contracts use solidity version higher than 0.5.4 the test command gives:
ParserError: Source file requires different compiler version (current compiler is 0.5.4+commit.7b0de266.mod.Emscripten.clang)

However the compile command works properly. 

**Sample code:**
```solidity
pragma solidity ^0.6.0;

abstract contract Context {
    function _msgSender() internal view virtual returns (address) {
        return msg.sender;
    }

    function _msgData() internal view virtual returns (bytes calldata) {
        return msg.data;
    }
}
```

### How it should work
The test command must take the solc version from the tronbox.js 
```json
compilers: {
      solc: {
          version: ">=0.6.0", 
      },
  },
```

### Cause of the problem
After investigating it seems that the test command first parses the contracts (Compile/parser.js) next compiles (Compile/index.js).
During parsing the options object is not passed so settings for the solc  verision are not available in the TronSolc.js, thus using the default version 0.5.4. In the second (compile) step they are available and it works properly. 

### Duplicate
This one is describing the same problem but without proper resolution:
https://github.com/tronprotocol/tronbox/issues/53

**Comment by llwslc** [comment]
Thanks. We will try to reproduce this problem

**Comment by GalinDinkov** [comment]
Problem seems to be in src\components\Compile\profiler.js line 225:

```javascript
find_contracts(options.base_path, function (err, allPaths) {
      if (err) return callback(err)

      // Include paths for Solidity .sols, specified in options.
      allPaths = allPaths.concat(paths)

      options.resolver.options = { networks: options.networks }
      self.dependency_graph(allPaths, options.resolver, function (err, dependsGraph) {
        if (err) return callback(err)

        findRequiredSources(dependsGraph, callback)
      })
    })
```

options.resolver doesn't include the options object which is later passed to:

```javascript
try {
      imports = Parser.parseImports(resolved_body, resolver.options)
    } catch (e) {
      e.message = 'Error parsing ' + import_path + ': ' + e.message
      return finished(e)
    }
```

(line 290)
