### ISSUE TITLE
Wrong enum argument is taking too much energy

### ISSUE THREAD

**Issue by Jutom17** [tronprotocol/tronbox#123]
**### Problem:**

My contract uses solidity version 0.5.15.

**Sample code:**

```
pragma solidity ^0.5.15;

enum Direction {
        HEAD,
        TAIL
    }
...
function betInstantTrx(Direction dir) external payable returns (uint result, bool isWin, uint payout, uint multiplier)
    {
        address payable gambler = msg.sender;

// Send the funds to gambler.
        sendFundsTrx(gambler, payout == 0 ? 0 : payout);
    }
```

So the enum Direction can be parsed with 0 or 1. But when I tried to pass a wrong value (ex: 2), it costs huge energy for a failed transaction. Can anyone have the explanation? Thanks. (and I'm sorry if it might be inappropriate to ask this question here)

**Comment by llwslc** [comment]
This is not caused by passing wrong value. It should be the use of assert() in the code. 

ref: https://docs.soliditylang.org/en/v0.5.15/control-structures.html#error-handling-assert-require-revert-and-exceptions
