### ISSUE TITLE
Migration error: has no value named "Receive"

### ISSUE THREAD

**Issue by Jutom17** [tronprotocol/tronbox#124]
I have set a directory for my project contract and I can compile without issues.
However when I want to run a migration I get the following error
```
Saving successful migration to network...
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying Dc...
ERROR: class org.tron.core.services.http.JsonFormat$ParseException : 1:3973: Enum type "protocol.SmartContract.ABI.Entry.EntryType" has no value named "Receive".
```
How can I resolve this? I think there is something wrong with the fallback function & tron-box because when I remove the fallback function, thing's fine.
```
    receive() external payable {}
```
I'm using solidity 0.6.12 with latest tronbox

**Comment by llwslc** [comment]
Please provide the network you are deploying to? mainnet, shasta or nile?

**Comment by Jutom17** [comment]
I was using trontools/quickstart. So that means this is private chain's issue.

**Comment by llwslc** [comment]
[trontools/quickstart](https://github.com/TRON-US/docker-tron-quickstart/issues/14)
Long time no update.
