### ISSUE TITLE
npm install -g tronbox not working

### ISSUE THREAD

**Issue by MikhilMC** [tronprotocol/tronbox#125]
I am using Ubuntu 20.04, with node.js version 10.24.1. When I do sudo npm install -g tronbox, I am getting this error.

> npm ERR! code 128
> npm ERR! An unknown git error occurred
> npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/web3-js/WebSocket-Node.git
> npm ERR! git@github.com: Permission denied (publickey).
> npm ERR! fatal: Could not read from remote repository.
> npm ERR! 
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-09-06T07_37_52_563Z-debug.log

Can anyone help me?

**Comment by llwslc** [comment]
Please try  this `npm cache clean --force` command.

**Comment by davinavarro998** [comment]
I have the same problem. Did you find a solution?
