### ISSUE TITLE
OpenZeppelin Truffle Upgrades plugin doesn't work

### ISSUE THREAD

**Issue by rubo** [tronprotocol/tronbox#129]
Currently, the [Truffle Upgrades](https://docs.openzeppelin.com/upgrades-plugins/1.x/truffle-upgrades) plugin doesn't work with TronBox and that turns the maintaining upgradable contracts on Tron into a nightmare. As the plugin requires Truffle v5.1.35 or later, l presume the problem could be in some old code in TronBox.

Any plans on support or recommendations on how to deal with this?

**Comment by llwslc** [comment]
Ok, we will check this problem. We will fix it as soon as possible or find other solutions.

**Comment by rubo** [comment]
Thanks, @llwslc.
One more question regarding Truffle compatibility. It would be super helpful to have supported the methods `at()` and `new()` for a contract artifact. The support of these methods has already been requested long ago [here](https://github.com/tronprotocol/tron-box/issues/30) and [here](https://github.com/tronprotocol/tron-box/issues/63) but it's pity we still don't have it. Currently, we have to use TronWeb if we want to interact with an already deployed contract but that requires too much code compared to the convenience of interacting with a contract artifact.
I think the support of these methods will come together with the fix of this issue as I noticed that OpenZeppelin's Upgrades plugin uses the `new()` method internally.

**Comment by llwslc** [comment]
After our hard work, we can't make the plugins work on Tronbox. Truffle and plugins are highly coupled.

Currently requires manual deployment of [proxy contracts](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/contracts/import.sol).

Tron is currently working on compatibility with the [ETH jsonrpc api](https://github.com/tronprotocol/java-tron/pull/4046), which will make it easier for us to use these tools in the future.

**Comment by robin-360Core** [comment]
TronBox, still not configured for proxy contract deployment.
