### ISSUE TITLE
connect ECONNREFUSED error during Tronbox migration

### ISSUE THREAD

**Issue by cloud9020locki** [tronprotocol/tronbox#132]
$ tronbox migrate
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
ERROR: connect ECONNREFUSED 127.0.0.1:9090

Hi, Can anybody tell me what is this? 
My network was this:
    development: {
      // For trontools/quickstart docker image
      privateKey: 'I import my private key here',
      userFeePercentage: 30,
      feeLimit: 100000000,
      fullHost: "http://127.0.0.1:9090",
      network_id: "*"
    }

**Comment by llwslc** [comment]
The recommendation is to use the shasta or nile network for testing.
