### ISSUE TITLE
tronwrap getCurrentBlock issue

### ISSUE THREAD

**Issue by martingg88** [tronprotocol/tronbox#134]
It seems the  tronWrap.trx.getCurrentBlock doesn't work and not even throw exception. As the code will stop immediately after 
"await tronWrap.trx.getCurrentBlock()". Any idea?

console.log("start1");
try{
      let b = await tronWrap.trx.getCurrentBlock();
}catch(err){
  console.log(err);
}
console.log(end2);
process.exit(0);

**Comment by llwslc** [comment]
What's the error message?

**Comment by martingg88** [comment]
sorry. my mistake. issued solved. many thanks
