### ISSUE TITLE
Change version of colors package or replace it

### ISSUE THREAD

**Issue by asinyagin** [tronprotocol/tronbox#135]
Colors package has a "bug". It prints infinite output. Details are here and all over the internet :) https://github.com/Marak/colors.js/issues/285.

I've set colors version to 1.4.0 to get tronbox working.

**Comment by llwslc** [comment]
[npm reverted 1.4.1, 1.4.2, and 1.4.44-liberty-2.
As a result, current latest version is 1.4.0.](https://github.com/Marak/colors.js/issues/285#issuecomment-1009437042)

Thanks!

**Comment by asinyagin** [comment]
Thank you!
