### ISSUE TITLE
Compilation of openzeppelin's ERC721 fails

### ISSUE THREAD

**Issue by asinyagin** [tronprotocol/tronbox#136]
I tried to compile NFT-contract based on ERC721 from openzeppelin, but it prints an error:
```
ubuntu@ubuntu-container:~/projects/nft-test1$ tronbox compile
Compiling ./contracts/NFT.sol...
Compiling @openzeppelin/contracts/token/ERC721/ERC721.sol...
Compiling @openzeppelin/contracts/token/ERC721/IERC721.sol...
Compiling @openzeppelin/contracts/token/ERC721/IERC721Receiver.sol...
Compiling @openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol...
Compiling @openzeppelin/contracts/utils/Address.sol...
Compiling @openzeppelin/contracts/utils/Context.sol...
Compiling @openzeppelin/contracts/utils/Strings.sol...
Compiling @openzeppelin/contracts/utils/introspection/ERC165.sol...
Compiling @openzeppelin/contracts/utils/introspection/IERC165.sol...

TypeError: Member "isContract" not unique after argument-dependent lookup in address.
   --> @openzeppelin/contracts/token/ERC721/ERC721.sol:388:13:
    |
388 |         if (to.isContract()) {
    |             ^^^^^^^^^^^^^
Compilation failed. See above.
```

Here's a repo with minimal code to reproduce the error https://github.com/asinyagin/nft-test1

I tried to compile it with solc 0.8.11, solcjs 0.8.6, truffle 5.3.29 and it works correctly.

Thank you!

**Comment by llwslc** [comment]
`isContract` is a members of address types in tron-solidity. This conflicts with ether-solidity.
See more:
https://github.com/tronprotocol/tips/issues/44

**Comment by asinyagin** [comment]
Oh, thank you! I've missed that info)

**Comment by dhruvja** [comment]
> `isContract` is a member of address type in tron-solidity. This conflicts with ether-solidity. See more: [tronprotocol/tips#44](https://github.com/tronprotocol/tips/issues/44)

So how can this be solved. How can i fix this error?

**Comment by llwslc** [comment]
@dhruvja 

The code of `isContract()` in the library needs to be changed to`isContract`.

**Comment by dhruvja** [comment]
> @dhruvja
> 
> The code of `isContract()` in the library needs to be changed to `isContract`.

i changed it to `isContract` and still getting same error.

before:
`if(to.isContract())`

After:
`if(to.isContract)`

Still getting the same error. What am i doing wrong?

**Comment by llwslc** [comment]
@dhruvja Try removing the `isContract` function from the `@openzeppelin/contracts/utils/Address.sol` file.

**Comment by dhruvja** [comment]
> @dhruvja Try removing the `isContract` function from the `@openzeppelin/contracts/utils/Address.sol` file.

there are many instances where `isContract` is used. Should it be changed everywhere? 

For example, there were some in `@openzeppelin/contracts/utils/Address.sol` which i changed. But then i am getting error for other occurences too like in `@openzeppelin/contracts/proxy/utils/Initializable.sol`. What should i do?

**Comment by llwslc** [comment]
@dhruvja Yes, you can see the changes here. https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3945/files
