### ISSUE TITLE
Having trouble in initializing a project in windows

### ISSUE THREAD

**Issue by miladganjali** [tronprotocol/tronbox#141]
Hello,
I successfully install tronbox on my PC but when I run the command `tronbox init`  the error below throw

my system 
windows 10
node v16.13.2
npm v8.1.2

I attach an npm log at end of this issue, and there is no package.json in the directory of the project I run the cmd in administer mode once again and the same error throw. 

```
Downloading...
Unpacking...
Setting up...
Error: Command failed: bash post-unpack.sh && rm post-unpack.sh && npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path E:\<path_to_project>\tron/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'E:\<path_to_project>\tron\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Local\npm-cache\_logs\2022-03-02T18_40_47_991Z-debug.log
```
[2022-03-02T18_40_47_991Z-debug.log](https://github.com/tronprotocol/tronbox/files/8172142/2022-03-02T18_40_47_991Z-debug.log)

**Comment by llwslc** [comment]
Please use node v14 first, we will solve the compatibility problem of node 16 as soon as possible.

**Comment by llwslc** [comment]
Does package.json exist in the `E:\<path_to_project>\tron\` folder?

**Comment by miladganjali** [comment]
no

**Comment by miladganjali** [comment]
No

**Comment by miladganjali** [comment]
@llwslc 
I use version 14 of node but still, there is no package.json in the directory
```
E:\Projects\solidity\tron>ls
contracts  migrations  package-lock.json  sample-env  test  tronbox-config.js  tronbox.js
```

**Comment by llwslc** [comment]
Windows will throw an exception for package.json not found, but that shouldn't affect anything. Try running `tronbox compile`, it should work fine.

**Comment by miladganjali** [comment]
![Untitled](https://user-images.githubusercontent.com/8298544/156571982-50fadd05-3622-4a1f-ab4a-e30f17faa778.png)

**Comment by llwslc** [comment]
Maybe this will help you. https://github.com/nodeschool/discussions/issues/1894

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and make sure you debug it with bech13.

**Comment by miladganjali** [comment]
still getting the same error, is there any other way for deploying the contract over the Tron network?
I have already deployed my contract on Ethereum and BSC by truffle.

**Comment by llwslc** [comment]
We also have two ways to deploy the contract.

http://www.tronide.io/
https://github.com/tronprotocol/wallet-cli

**Comment by Yuxanju** [comment]
You will need to synchronize your wallet and then you debug it

**Comment by miladganjali** [comment]
@Yuxanju I did what u asking but got the same error. I am using the editor is simpler than this repo.

**Comment by Yuxanju** [comment]
You didn’t follow the link cause I never send you any link.. how did you do
what I asked you to do and you didn’t get any result

**Comment by miladganjali** [comment]
@Yuxanju, send me the link, but I put all of the wallet data in the .env file like in the documentation.

**Comment by Yuxanju** [comment]
www.ellipalsuites.com

**Comment by Yuxanju** [comment]
Did you get any response?

**Comment by llwslc** [comment]
> @Yuxanju, send me the link, but I put all of the wallet data in the .env file like in the documentation.

Please do not use wallets of unknown origin.

**Comment by Yuxanju** [comment]
www.ellipalsuites.com

**Comment by Yuxanju** [comment]
Let me know the response you get

**Comment by miladganjali** [comment]
thank u @llwslc I report his account, I didn't use his link.

**Comment by Meharab** [comment]
I'm have the same issue @miladganjali @llwslc @sullof ... what's the solution?
https://github.com/tronprotocol/tronbox/issues/154#issue-1324326186
