### ISSUE TITLE
not able to deploy contract

### ISSUE THREAD

**Issue by HARSHisawesome2** [tronprotocol/tronbox#145]
tronbox migrate --network shasta
ERROR: It was not possible to instantiate TronWeb. Some required parameters are missing in your "tronbox.js".

this is my tronbox.js 

const port = process.env.HOST_PORT || 9090

module.exports = {
  networks: {
    mainnet: {
      // Don't put your private key here:
      privateKey: process.env.PRIVATE_KEY_MAINNET,
      /*
Create a .env file (it must be gitignored) containing something like

  export PRIVATE_KEY_MAINNET=4E7FECCB71207B867C495B51A9758B104B1D4422088A87F4978BE64636656243

Then, run the migration with:

  source .env && tronbox migrate --network mainnet

*/
      userFeePercentage: 100,
      feeLimit: 1000 * 1e6,
      fullHost: 'https://api.trongrid.io',
      network_id: '1'
    },
    shasta: {
      privateKey: process.env.PRIVATE_KEY_SHASTA,
      userFeePercentage: 50,
      feeLimit: 1000 * 1e6,
      fullHost: 'https://api.shasta.trongrid.io',
      network_id: '2'
    },
    nile: {
      privateKey: process.env.PRIVATE_KEY_NILE,
      userFeePercentage: 100,
      feeLimit: 1000 * 1e6,
      fullHost: 'https://api.nileex.io',
      network_id: '3'
    },
    development: {
      // For trontools/quickstart docker image
      privateKey: 'da146374a75310b9666e834ee4ad0866d6f4035967bfc76217c5a495fff9f0d0',
      userFeePercentage: 0,
      feeLimit: 1000 * 1e6,
      fullHost: 'http://127.0.0.1:' + port,
      network_id: '9'
    },
    compilers: {
      solc: {
        version: '0.8.6'
      }
    }
  },
  // solc compiler optimize
  solc: {
  //   optimizer: {
  //     enabled: true,
  //     runs: 200
  //   },
  //   evmVersion: 'istanbul'
  }
}

**Comment by llwslc** [comment]
You may not have set the `PRIVATE_KEY_SHASTA` in the .env file

**Comment by HARSHisawesome2** [comment]
i have done it already

**Comment by HARSHisawesome2** [comment]
please help  @llwslc

**Comment by llwslc** [comment]
https://github.com/tronprotocol/tronbox/blob/master/src/components/TronWrap/index.js#L78

This error is because the privateKey or fullHost is not set.

**Comment by HARSHisawesome2** [comment]
oh how to fix that

**Comment by llwslc** [comment]
Create a .env file (it must be gitignored) containing something like

export PRIVATE_KEY_SHASTA ='your private key'

Then, run the migration with:

source .env && tronbox migrate --network shasta

**Comment by HARSHisawesome2** [comment]
ok trying it

**Comment by HARSHisawesome2** [comment]
![Screenshot 2022-05-10 132236](https://user-images.githubusercontent.com/103326606/167577598-669c24da-6789-4ac1-aee5-1a514c6a1e03.png)


![now](https://user-images.githubusercontent.com/103326606/167577935-387da965-a577-4f75-8b11-6f6053da9ef6.png)


@llwslc i added but still doesnt works

**Comment by HARSHisawesome2** [comment]
![current](https://user-images.githubusercontent.com/103326606/167582879-378454be-2642-4a26-b3a0-b55e7284b811.png)
not able to understand i am deploying in it shasta network but it using devlopment network i already have created .env 

this is my tronbox .js

const port = process.env.HOST_PORT || 9090

module.exports = {
  networks: {
    mainnet: {
      // Don't put your private key here:
      privateKey: process.env.PRIVATE_KEY_MAINNET,
      /*
Create a .env file (it must be gitignored) containing something like

  export PRIVATE_KEY_MAINNET=4E7FECCB71207B867C495B51A9758B104B1D4422088A87F4978BE64636656243

Then, run the migration with:

  source .env && tronbox migrate --network mainnet

*/
      userFeePercentage: 100,
      feeLimit: 1000 * 1e6,
      fullHost: 'https://api.trongrid.io',
      network_id: '1'
    },
    shasta: {
      privateKey: process.env.PRIVATE_KEY_SHASTA,
      userFeePercentage: 50,
      feeLimit: 1000 * 1e6,
      fullHost: 'https://api.shasta.trongrid.io',
      network_id: '2'
    },
    nile: {
      privateKey: process.env.PRIVATE_KEY_NILE,
      userFeePercentage: 100,
      feeLimit: 1000 * 1e6,
      fullHost: 'https://api.nileex.io',
      network_id: '3'
    },
    development: {
      // For trontools/quickstart docker image
      privateKey: 'da146374a75310b9666e834ee4ad0866d6f4035967bfc76217c5a495fff9f0d0',
      userFeePercentage: 0,
      feeLimit: 1000 * 1e6,
      fullHost: 'http://127.0.0.1:' + port,
      network_id: '9'
    },
    compilers: {
      solc: {
        version: '0.8.6'
      }
    }
  },
  // solc compiler optimize
  solc: {
  //   optimizer: {
  //     enabled: true,
  //     runs: 200
  //   },
  //   evmVersion: 'istanbul'
  }
}





@llwslc

**Comment by llwslc** [comment]
Please enter the correct command.

```
tronbox migrate --network shasta
```

**Comment by HARSHisawesome2** [comment]
hmm

**Comment by HARSHisawesome2** [comment]
[image: h.png]

this comes when i run it

**Comment by HARSHisawesome2** [comment]
https://user-images.githubusercontent.com/103326606/167613255-bd13893f-fe78-4c7f-a77b-a694db98ae32.png
this comes now

**Comment by llwslc** [comment]
Try modify the `tronbox.js` directly.

```
shasta: {
  privateKey: 'fill in your private key',
  userFeePercentage: 50,
  feeLimit: 1000 * 1e6,
  fullHost: 'https://api.shasta.trongrid.io/',
  network_id: '2'
},
```

**Comment by HARSHisawesome2** [comment]
yes works now thanks a lot @llwslc for your effort

**Comment by HARSHisawesome2** [comment]
tronbox migrate -- network shasta
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
ERROR: connect ECONNREFUSED 127.0.0.1:9090
PS C:\Users\bq562ts\Downloads\alltest\res> 

@llwslc the error is again coming up :(
