### ISSUE TITLE
Contract Migrations.sol is not nessesary for migrations to work

### ISSUE THREAD

**Issue by Pafaul** [tronprotocol/tronbox#146]
There is a problem with current migrations routine in tronbox. \
Problem: smart-contract Migrations.sol is NOT ESSENTIAL for migration process. It may be done with or without this smart contract.

Scenario: 
- Project with smart contracts was created without usage of ```tronbox init```
- ```tronbox.js``` and migration files were added manually

When launching custom migrations following error occures: ```Could not find artifacts for Migrations from any sources``` \
Which indicates that requirement for contract ```Migrations.sol``` is hardcoded somewhere
Indeed, without this smart contract migrations cannot be finished, because there is hardcoded ```resolver.require``` inside ```Migrate/index.js```: https://github.com/tronprotocol/tronbox/blob/a81fd84f3869b708025b6ecec5784623847c5a99/src/components/Migrate/index.js#L49

I think that this library is general purpose and MUST account for projects that are willing to use custom migration processes.

Suggestions what to do with this problem:
- Add ```boolean``` option ```use_default_migration_contract``` that will try to load ```Migrations.sol``` contract
- Remove loading of contract ```Migrations.sol``` completely and let developers decide migration logic
- Add try/catch so in case of ```Migrations.sol``` absence migrations could continue and do not fail with error

**Comment by llwslc** [comment]
Thanks for the suggestion, we will investigate this issue as soon as possible.

**Comment by DemigodHA** [comment]
TR8NC5h27x55STKcRoBpK7LfNqQt4vvQ7M

**Comment by Pafaul** [comment]
Further investigation of truffle showed that Migrations.sol is deeply integrated inside truffle workflow, as truffle is used as inspiration for tronbox this may affect workflow in unpredictable ways, issue is irrelevant.
