### ISSUE TITLE
Not enough info on TronWrap initialization fail

### ISSUE THREAD

**Issue by Pafaul** [tronprotocol/tronbox#147]
Initialization of ```tronweb``` is performed in ```TronWrap/index.js```:
https://github.com/tronprotocol/tronbox/blob/d3b76ed2ebb0b5020341563fd639d3b39a1a8a9f/src/components/TronWrap/index.js#L82

If not all required options are provided in config file ```tronweb.js``` than following error message appears:
https://github.com/tronprotocol/tronbox/blob/d3b76ed2ebb0b5020341563fd639d3b39a1a8a9f/src/components/TronWrap/index.js#L78

In this case it just says ```Some required parameters``` without any specification, but in this case it must be more specific - what options were absent?

Suggestions:
- Add OptionChecker object that will perform options check before passing them further and will be able to construct correct error messages

**Comment by llwslc** [comment]
Very good improvement
