### ISSUE TITLE
not able to deploy contract i have enough funds

### ISSUE THREAD

**Issue by HARSHisawesome2** [tronprotocol/tronbox#151]
RROR: Contract Migrations has not been deployed on the network.
For more details, check the transaction at:
https://api.shasta.trongrid.io//wallet/gettransactionbyid?value=0267da6332f0dcedbef18775b9cd9bf9877f0915667ecdd72ea6540d30263bed
If the transaction above is empty, most likely, your address had no bandwidth/energy to deploy the contract.
PS C:\Users\bq562ts\Downloads\TRONDEV - Copy\res> 

[migration.zip](https://github.com/tronprotocol/tronbox/files/9018179/migration.zip)
this has my migrations . pls help out

**Comment by HARSHisawesome2** [comment]
also , 
when i import openzippline contracts i think they are compiled in 0.8.1 how to deploy it

Error parsing @openzeppelin\contracts\utils\Address.sol: ParserError: Source file requires different compiler version (current compiler is 0.8.0+commit.7c2e6412.Emscripten.clang) - note that nightly builds are considered to be strictly less than the released version
 --> ParsedContract.sol:4:1:
  |
4 | pragma solidity ^0.8.1;
  | ^^^^^^^^^^^^^^^^^^^^^^^

**Comment by llwslc** [comment]
This should be a network issue.
