### ISSUE TITLE
ContractArtifacts.at(address) is not supported

### ISSUE THREAD

**Issue by prasad-kumkar** [tronprotocol/tronbox#156]
Contract.at() doesn't seem to be supported for now. Would be really helpful if support is added

Error: The construct contractArtifacts.at(address) is not currently supported by TronBox. It will be in the future. Stay in touch

<img width="804" alt="image" src="https://user-images.githubusercontent.com/43164022/194593414-b8bc766b-9fba-40b9-ad7d-00a3882531a6.png">

**Comment by llwslc** [comment]
Thank you, we will support this as soon as possible, please use the following code first.

```js
tronWrap.contract().at(address)
```
