### ISSUE TITLE
yarn/npm can't install latest version tronbox(3.0.0)

### ISSUE THREAD

**Issue by fooabc** [tronprotocol/tronbox#167]
Use `yarn global add tronbox` or  `npm install -g tronbox` installed tronbox version is 2.7.25 not latest version 3.0.0, 

`yarn info tronbox` return info is: 
![图片](https://user-images.githubusercontent.com/110512690/201891866-727df9a8-55db-4b6e-84ce-c13534ebf465.png)

in npmjs.com can see the version of 3.0.0: 

![图片](https://user-images.githubusercontent.com/110512690/201892291-e8127964-4a5e-40c1-baf3-4d14e7b29a11.png)

**Comment by llwslc** [comment]
Is your npm registry set up incorrectly?

https://docs.npmjs.com/cli/v8/using-npm/registry

**Comment by fooabc** [comment]
> 

My bad, reset the default registry it works

thanks
