### ISSUE TITLE
PayloadTooLargeError: request entity too large on Migration to devnet

### ISSUE THREAD

**Issue by gfijrb** [tronprotocol/tronbox#19]
Hi. I have this error POST 413 1049 - 0.834 ms

PayloadTooLargeError: request entity too large 
    at readStream (/tron/app/node_modules/raw-body/index.js:155:17)
    at getRawBody (/tron/app/node_modules/raw-body/index.js:108:12)
    at read (/tron/app/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/tron/app/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/tron/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/tron/app/node_modules/express/lib/router/index.js:317:13)
    at /tron/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/tron/app/node_modules/express/lib/router/index.js:335:12)
    at next (/tron/app/node_modules/express/lib/router/index.js:275:10)
    at logger (/tron/app/node_modules/morgan/index.js:144:5)

Deployed only two contracts

root@user:~/Desktop/chbets_contracts$ tronbox migrate --reset --network development --limit 100
// pk
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  Migrations:
    (base58) TPY9bGPSj2xZ3drsWHCg9u9FWJr4SJvyye
    (hex) 4194d483e5535e487a7348f18699918b6111316b61
Saving successful migration to network...
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Replacing Affiliates...
  Affiliates:
    (base58) TMzWaw5WSbqokxsbs3mWF2oKeaZFWpCkC4
    (hex) 4183e09a918035624e0b05e322ec50d4cd419f03ce
Saving successful migration to network...
Saving artifacts...
Running migration: 3_deploy_contracts.js
  Running step...
  Deploying SafeMath...
  SafeMath:
    (base58) TN8E32RjP3dsNLB167eUTWLM1ow6B1tR63
    (hex) 4185561dba165a6af2bdd6d8ca5d2fb53a17288001
  Linking SafeMath to Test
  Deploying Test...

// failed here 

Can you fix it or give me the way to solve it manually.
System Nodejs v.8.16, Ubuntu16.04

PS. Not compiled on W10 and Mac.

**Comment by shenyongri110** [comment]
@gfijrb Based on your error log, It looks like your app express framework response this error, not tronbox. Tronbox doesn't use express framework inside. When you send post request, you can try to config express body size to solve it. For example,
```
app.use(bodyParser.json({limit: '10mb', extended: true}))
app.use(bodyParser.urlencoded({limit: '10mb', extended: true}))
```

**Comment by gfijrb** [comment]
> @gfijrb Based on your error log, It looks like your app express framework response this error, not tronbox. Tronbox doesn't use express framework inside. When you send post request, you can try to config express body size to solve it. For example,
> 
> ```
> app.use(bodyParser.json({limit: '10mb', extended: true}))
> app.use(bodyParser.urlencoded({limit: '10mb', extended: true}))
> ```

ok thanks, but it log from console of tronbox generated project and I didnt found there config for memory limit and didnt use express indeed.
