### ISSUE TITLE
Add contract verification method to TronBox

### ISSUE THREAD

**Issue by NatashkinAlex** [tronprotocol/tronbox#191]
Hello! I'd like to suggest adding a method for contract verification directly to TronBox. This would simplify the verification process for developers and enhance the usability of the tool. It might be worth considering integration with the Tronscan API for automatic contract verification after deployment. I'd be happy to discuss possible approaches and solutions if this is relevant for the project. Thank you!

**Comment by llwslc** [comment]
Thanks! We are developing the contract flatten method, after which we will develop the contract verification method.

**Comment by ericobi** [comment]
Any updates on this @llwslc ?
