### ISSUE TITLE
How to import dependencies which are not available in npm registry

### ISSUE THREAD

**Issue by dhruvja** [tronprotocol/tronbox#201]
I was deploying some contracts written on solidity for EVM on tron. I changed all the things that were needed for the file to compile. But i was unable to download some dependencies which are not available on npm like

`import { ClonesWithImmutableArgs } from "@cwia/ClonesWithImmutableArgs.sol"`
`import { Bytes32AddressLib } from "@rari-capital/solmate/src/utils/Bytes32AddressLib.sol"`

Since the above contracts are not deployed on TVM, should i deploy, download and use them in a relative path?

**Comment by llwslc** [comment]
Of course, you can write the code directly in the source code file.

**Comment by llwslc** [comment]
If you have source files, you can store them in the same directory. Import these files like the following.

```sol
import { ClonesWithImmutableArgs } from "./ClonesWithImmutableArgs.sol"
import { Bytes32AddressLib } from "./Bytes32AddressLib.sol"
```

**Comment by dhruvja** [comment]
Thanks a lot , this solved the issue.
