### ISSUE TITLE
Getting `zsh: bus error ` while running `tronbox compile --all`

### ISSUE THREAD

**Issue by dhruvja** [tronprotocol/tronbox#202]
I am compiling a quite a few contracts which are written on EVM. I have modified the contracts so that they can be deployed on tron.

But when i try to compile the contracts using this command: `tronbox compile --all`
It compile a bunch of contracts but then fails with the following error
```
zsh: bus error  tronbox compile --all
```

I even tried with sudo and `tronbox compile` but it is giving me the same error. Any help would be appreciated.

**Comment by llwslc** [comment]
@dhruvja 
Could you show us your version of node.js, system and tronbox?

For more information on this issue, please refer to this link.

https://stackoverflow.com/questions/73022976/bus-error-when-running-npm-run-dev-npm-start

**Comment by llwslc** [comment]
@dhruvja  I think maybe you need to reinstall tronbox , instead of deleting the `node_modules` folder.

```
npm uninstall -g tronbox
npm installl -g tronbox
```

**Comment by dhruvja** [comment]
> npm uninstall -g tronbox

I tried but i am getting the same error lol. Wonder what is going wrong?

**Comment by llwslc** [comment]
@dhruvja Also try to reboot the computer.

**Comment by dhruvja** [comment]
i am getting this error now: `RuntimeError: memory access out of bounds` after a whole lot of gibberish being printed. Does it have to do smtg with my machine not supporting it. And also i am compiling a lot of contracts too.

Machine configuration:
Disk space: 512 GB SSD
Ram: 16 GB
Cores: 10 CPU cores
Processor: M1 Pro
OS: Mac Os ventura.

**Comment by llwslc** [comment]
@dhruvja This is a compilation error, as your contract file is too large and therefore out of memory.
