### ISSUE TITLE
tronbox compile error 

### ISSUE THREAD

**Issue by highRisk911** [tronprotocol/tronbox#204]
Hi there! 

I had tried run repo https://github.com/tronsuper/metacoin-box

After `npm install -g tronbox` i used `tronbox compile` and get next error: 

```
Error: Package subpath './secp256k1' is not defined by "exports" in /usr/local/lib/node_modules/tronbox/node_modules/ethereum-cryptography/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:731:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /usr/local/lib/node_modules/tronbox/node_modules/tronweb/dist/webpack:/tronweb/external commonjs "ethereum-cryptography/secp256k1":1:38
```

My config m1 air, ventura: 

```
{
  npm: '8.5.0',
  node: '16.14.2',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1n+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

```

Unfortunately `npm uninstall -g tronbox` doesn't make effect.

**Comment by Vivecboots** [comment]
I too am having compile issues with metacoin and tronbox download in general right now.  Ive tried many variations.  Ive replaced modules and everything.  

MetaCoin> tronbox compile

Error: Error parsing /Users/x/OneDrive/Desktop/box/MetaCoin/contracts/ConvertLib.sol: Cannot find module 'C:\Users\x\.tronbox\solc\soljson_v0.5.4.js'

Require stack:
.....

**Comment by llwslc** [comment]
The problem has now been fixed. Please reinstall tronbox.

https://github.com/ethereum/js-ethereum-cryptography/issues/88

**Comment by llwslc** [comment]
> I too am having compile issues with metacoin and tronbox download in general right now. Ive tried many variations. Ive replaced modules and everything.
> 
> MetaCoin> tronbox compile
> 
> Error: Error parsing /Users/x/OneDrive/Desktop/box/MetaCoin/contracts/ConvertLib.sol: Cannot find module 'C:\Users\x.tronbox\solc\soljson_v0.5.4.js'
> 
> Require stack: .....

@Vivecboots Is there a `.tronbox` folder in the home directory?
