### ISSUE TITLE
tronbox compile with new .transferToken or .tokenBalance

### ISSUE THREAD

**Issue by JoeGonzalez0886** [tronprotocol/tronbox#21]
trying to compile with functions that use transferToken or tokenBalance fails with the below comments.

**TypeError: Member "transferToken" not found or not visible after argument-dependent lookup in address.**

**Comment by kleoken** [comment]
Can you post an example of your code?

**Comment by swatim2020** [comment]
> trying to compile with functions that use transferToken or tokenBalance fails with the below comments.
> 
> **TypeError: Member "transferToken" not found or not visible after argument-dependent lookup in address.**

have you got any solution on it?

**Comment by llwslc** [comment]
> 

Are you using tron solidity compiler?

**Comment by llwslc** [comment]
> > trying to compile with functions that use transferToken or tokenBalance fails with the below comments.
> > **TypeError: Member "transferToken" not found or not visible after argument-dependent lookup in address.**
> 
> have you got any solution on it?

Are you using tron solidity compiler?
