### ISSUE TITLE
How to get the address of deployed contract in a different file?

### ISSUE THREAD

**Issue by dhruvja** [tronprotocol/tronbox#212]
I am using migrations to deploy my contracts. I have quite a few contracts to deploy and some contracts take some arguments when deploying. Some of the arguments can be the address of the previously deployed contract. How can i get the address of the previously deployed contract so i can pass it as an argument while deploying the contract.

**Comment by llwslc** [comment]
@dhruvja Please refer to the following code.


```javascript
const Migrations = artifacts.require('./Migrations.sol');

module.exports = async deployer => {
  await deployer.deploy(Migrations);
  const migrations = await Migrations.deployed();
  console.log(migrations.address);
};

```

**Comment by dhruvja** [comment]
> @dhruvja Please refer to the following code.
> 
> ```js
> const Migrations = artifacts.require('./Migrations.sol');
> 
> module.exports = async deployer => {
>   await deployer.deploy(Migrations);
>   const migrations = await Migrations.deployed();
>   console.log(migrations.address);
> };
> ```

Suppose i deploy a contract in a different file. How can i get that address? Should i store it explicitly?

**Comment by llwslc** [comment]
@dhruvja Just delete the deployment code.

```javascript
const Migrations = artifacts.require('./Migrations.sol');

module.exports = async function (deployer) {
  const migrations = await Migrations.deployed();
  console.log(migrations.address);
};
```

**Comment by mahmod87** [comment]
A

**Comment by dhruvja** [comment]
> A

what?????

**Comment by llwslc** [comment]
@dhruvja See this code.

```javascript
const Migrations = artifacts.require('./Migrations.sol');

module.exports = async function (deployer) {
  const migrations = await Migrations.deployed();
  await migrations.methodName();
};
```

**Comment by dhruvja** [comment]
> @dhruvja See this code.
> 
> ```js
> const Migrations = artifacts.require('./Migrations.sol');
> 
> module.exports = async function (deployer) {
>   const migrations = await Migrations.deployed();
>   await migrations.methodName();
> };
> ```

Thanks a lot.
