### ISSUE TITLE
tronbox verification methods, hardhat support

### ISSUE THREAD

**Issue by ericobi** [tronprotocol/tronbox#217]

**Comment by ericobi** [comment]
And I would like to know the updates about the verification method, too. #191 
Thanks a lot

**Comment by llwslc** [comment]
@ericobi 

Please use the [flatten](https://developers.tron.network/reference/flattening-your-contracts) command to get the contract file that needs to be verified, and upload the file on [tronscan](https://tronscan.org/#/contracts/verify).
