### ISSUE TITLE
Getting 405 error on /wallet/getBlock/ on migrate command

### ISSUE THREAD

**Issue by imanashoorii** [tronprotocol/tronbox#218]
I faced the error below when I tried to call migrate command with tronbox:

```
FULL-NODE /wallet/getblock 
[Output] <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /wallet/getblock. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
```

there is nothing related to this problem in your project doc.
appreciate your help.

**Comment by llwslc** [comment]
which network? @imanashoorii

**Comment by imanashoorii** [comment]
I got this error with every network that I tried even with *metacoin* in tronbox documentation.

**Comment by llwslc** [comment]
I just ran it again, and there is no problem, what is your tronbox version? @imanashoorii

**Comment by imanashoorii** [comment]
I`ve just able to fix it with image *tronbox/tre* and now everything works fine, I used *tronbox/quickstart* and got that error. Thanks for your quick response.
