### ISSUE TITLE
Cannot use all accounts in migrations

### ISSUE THREAD

**Issue by kleoken** [tronprotocol/tronbox#26]
```
module.exports = function(deployer, network, accounts) {
  console.log("accounts: ", accounts);
  deployer.deploy(Migrations);
  deployer.deploy(Contract1, accounts[0], accounts[0]);
};
```

`accounts` only returns the very first account and not the entire array and `accounts[0]` returns the first character

**Comment by sullof** [comment]
The PR at https://github.com/TRON-US/tronbox/pull/46 should have solved this. 
Install tronbox@2.7.9. Feel free to reopen this issue if the problem is not fixed.

**Comment by partywave** [comment]
all accounts are available as an array in tests but only the deployer account is provided in migrations
