### ISSUE TITLE
payable address is broken in tronbox 2.5.2

### ISSUE THREAD

**Issue by forhas** [tronprotocol/tronbox#43]
Trying to compile my project using command `source ./.env && tronbox compile --compile-all --reset` and getting 

```
Error parsing C:\dev\..\smart-contract\contracts\MyContract.sol: ParsedContract.sol:57:49: ParserError: Expected ')' but got 'payable'
    mapping(string => address payable) private membersAccounts;
```

The top line of my contract is `pragma solidity ^0.5.4;`
My tronbox.js file contains:

```
    compilers: {
      solc: {
         version: '0.5.4'
      }
    }
```

And my tronbox version is 2.5.2

@sullof

**Comment by sullof** [comment]
That looks like a problem with the compiler and does not depend on tronbox itself (the compilers are part of javatron.) May you share the code causing the issue with me so that I can take a closer look?
