### ISSUE TITLE
Linux install tronbox failed

### ISSUE THREAD

**Issue by zem007** [tronprotocol/tronbox#45]
**npm install -g tronbox** 
_got error:_

npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated truffle-contract@4.0.30: WARNING: This package has been renamed to @truffle/contract.
npm WARN deprecated truffle-error@0.0.5: WARNING: This package has been renamed to @truffle/error.
npm WARN deprecated truffle-blockchain-utils@0.0.10: WARNING: This package has been renamed to @truffle/blockchain-utils.
npm WARN deprecated truffle-contract-schema@3.0.13: WARNING: This package has been renamed to @truffle/contract-schema.
npm WARN deprecated truffle-interface-adapter@0.2.5: WARNING: This package has been renamed to @truffle/interface-adapter.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/node-v6/bin/tronbox -> /usr/local/node-v6/lib/node_modules/tronbox/build/tronbox.js

> keccak@1.4.0 install /usr/local/node-v6/lib/node_modules/tronbox/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

> keccak@1.4.0 rebuild /usr/local/node-v6/lib/node_modules/tronbox/node_modules/keccak
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.10.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/node-v6/lib/node_modules/tronbox/node_modules/keccak/.node-gyp"
make: Entering directory `/usr/local/node-v6/lib/node_modules/tronbox/node_modules/keccak/build'
  CXX(target) Release/obj.target/keccak/src/addon.o
make: g++: Command not found
make: *** [Release/obj.target/keccak/src/addon.o] Error 127
make: Leaving directory `/usr/local/node-v6/lib/node_modules/tronbox/node_modules/keccak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node-v6/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-514.26.2.el7.x86_64
gyp ERR! command "/usr/local/node-v6/bin/node" "/usr/local/node-v6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/node-v6/lib/node_modules/tronbox/node_modules/keccak
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/usr/local/node-v6/bin/node" "/usr/local/node-v6/bin/npm" "run" "rebuild"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keccak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keccak
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keccak
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/node-v6/lib/node_modules/tronbox/node_modules/keccak/npm-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

> websocket@1.0.29 install /usr/local/node-v6/lib/node_modules/tronbox/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/node-v6/lib/node_modules/tronbox/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/usr/local/node-v6/lib/node_modules/tronbox/node_modules/websocket/build'

> core-js@2.6.11 postinstall /usr/local/node-v6/lib/node_modules/tronbox/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

and **tronbox compile** got error too

_error:_
usr/local/node-v6/lib/node_modules/tronbox/node_modules/find-up/index.js:8
module.exports = async (name, options = {}) => {
                       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/node-v6/lib/node_modules/tronbox/build/components/Config.js:1:245)
[root@VM_175_27_centos TronJoke]# npm start run

> tron-messageboard@0.1.0 start /home/gitdapp/TronJoke
> react-scripts start "run"

sh: react-scripts: command not found

npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/usr/local/node-v6/bin/node" "/usr/local/node-v6/bin/npm" "start" "run"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! tron-messageboard@0.1.0 start: `react-scripts start "run"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the tron-messageboard@0.1.0 start script 'react-scripts start "run"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tron-messageboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start "run"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tron-messageboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tron-messageboard
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:

how too fix that?

thanks a lot

**Comment by sullof** [comment]
That looks like a permission issue. I suggest that you install Node using Nvm (https://github.com/nvm-sh/nvm), which offers many advantage (install node not as root, allow multiple versions, etc.) and try again.
Let me know if the issue persists.

**Comment by zem007** [comment]
> That looks like a permission issue. I suggest that you install Node using Nvm (https://github.com/nvm-sh/nvm), which offers many advantage (install node not as root, allow multiple versions, etc.) and try again.
> Let me know if the issue persists.

@sullof sounds good! I will try that, thanks a lot.
