### ISSUE TITLE
can't use all the accounts as owner in tronbox test

### ISSUE THREAD

**Issue by raedon707** [tronprotocol/tronbox#48]
I was writing test cases for my contract.
and I needed to switch the owner account to access the contract functions. 

tronbox only picks the first account (accounts[0]) as the owner.
I don't see any way to switch the owner's account other than changing the private key in tronbox config file.
(sending `{ from: address }` with a transaction is not working (it worked with truffle))

**Comment by sullof** [comment]
The owner is the address that deploys the contract, which using Tronbox is accounts[0].
I guess you should add a function in your contract to change the owner.

**Comment by raedon707** [comment]
@sullof Yes, I've added a function to change the owner.  
But when I transfer ownership to account[1] or any other listed account, I can not use that to call any function. 

let's say i have a function which only returns the address of the caller of that function. 
``` 
function test() public view returns(address sender) {
    sender = msg.sender;
}
```

now, in test cases, this function will always return the address of accounts[0]. I simply can not make a call from other accounts.
