### ISSUE TITLE
Compile issue on Windows 10 in Tronbox > 2.5.2

### ISSUE THREAD

**Issue by wavemotionio** [tronprotocol/tronbox#50]
There appears to be an issue with newer versions that invalidate the instructions provided in https://github.com/Tronbox-boxes/metacoin-box.  The compilation error is explained in this stackoverflow post. In summary, the fix is to revert back to `npm install tronbox@2.5.2 -g`

https://stackoverflow.com/questions/59256712/tronbox-compile-issue/59282130#59282130

**Comment by sullof** [comment]
@wavemotionio Try a most recent version. The 2.7.10 should work fine.

**Comment by sullof** [comment]
The problem with version 2.5.2 is that it does not support important changes in the Tron platform.

**Comment by Madeindreams** [comment]
I just installed 2.7.13 and there is now solc version that are passing. I'm unable to compile.

Error:
TronBox supports only the following versions:
0.4.24 - 0.4.25 - 0.5.4 - 0.5.8 - 0.5.10

**Comment by Madeindreams** [comment]
To fix this issue you must manually download the compile. For some reason tronbox is not able to do it by himself.

In the console, type;
tronbox --download-compiler 0.5.10
