### ISSUE TITLE
Test suite requires solc 0.5.4 or earlier

### ISSUE THREAD

**Issue by bondibox** [tronprotocol/tronbox#53]
When creating contracts with tronbox v2.7.10 `tronbox test` does not run unless the solc declaration is 0.5.4 or earlier. However,  `tronbox compile` command works O.K. 

My contract begins with `pragma solidity ^0.5.8;` and my tronbox.js includes `compilers: {    solc: {    version: '0.5.8'   }  }`

The error message is

> Error parsing [...]/contracts/Agile.sol: ParsedContract.sol:2:1: 
> ParserError: Source file requires different compiler version (current compiler is 0.5.4+commit.7b0de266.mod.Emscripten.clang)

When those values are changed to 0.5.4 the response is

>   6 passing (9s)

**Comment by llwslc** [comment]
That looks like a problem with the compiler and does not depend on tronbox itself (the compilers are part of javatron.) May you share the code causing the issue with me so that I can take a closer look?
