### ISSUE TITLE
Allow test_dictionary to be modified via configuration

### ISSUE THREAD

**Issue by JayArrowz** [tronprotocol/tronbox#54]
At the moment i have a project setup with my tests being in folder:
"/tests/contracts/XXXContractTest.js"

However i have to run all the tests file by file cause tronbox test does not support wildcards like: "tronbox test /test/contracts/*.js"

Either make wildcard + folder support for the tronbox test argument, or allow to set the below configuration via tronbox-config.js.

https://github.com/TRON-US/tronbox/blob/8d9860e28bce460cdfebb2a3df3d6048c2c9ab50/src/components/Config.js#L94

**Comment by llwslc** [comment]
Thanks, we will solve this ASAP.
