### ISSUE TITLE
Error on passing BigNumber to tronWeb.utils.abi.encodeParams

### ISSUE THREAD

**Issue by JayArrowz** [tronprotocol/tronbox#56]
Code in question:
```
var sig = await tronWeb.trx.signMessage(tronWeb.sha3("TestSeed"));
var commit = tronWeb.utils.abi.encodeParams(['uint256'], [tronWeb.toBigNumber(sig)]);
```

The error also happens if i do:
```
tronWeb.utils.abi.encodeParams(['uint256'], [sig]);
```

Error:
![image](https://user-images.githubusercontent.com/49910176/78455836-6a5fef00-7698-11ea-9240-403a5b81319e.png)

**Comment by llwslc** [comment]
This sig is larger than the maximum value of uint256, which cannot be supported.
