### ISSUE TITLE
Tronbox 'test' command deploy migrations only once.

### ISSUE THREAD

**Issue by MentatX** [tronprotocol/tronbox#58]
`
tronbox test
`

Tronbox **test** command must re-deploy all of migrations at the beginning of every test file to ensure you have a fresh set of contracts to test against. But the migrations are deployed only once.
**contract()** function in test does not work properly...

Tronbox v2.7.4
Solidity v0.5.8 (tron-solc)

**Comment by folowing** [comment]
> **contract()** function in test does not work properly...
Please add more detail about this issue.
