### ISSUE TITLE
compile contracts with bytecode "0x"

### ISSUE THREAD

**Issue by pironmind** [tronprotocol/tronbox#59]
Bug report!

Machine node12, solc0.5.10, ubuntu19/windows10, tronbox2.7.12

When I compile the code i get in build .json this result for bytecode

```
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "sourceMap": "",
  "deployedSourceMap": "",
```

My contract 

```
pragma solidity ^0.5.8;

import "../../../contracts/tokens/trc20/TRC20.sol";
import "../../../contracts/tokens/trc20/TRC20Mintable.sol";
import "../../../contracts/tokens/trc20/TRC20Detailed.sol";
import "../../../contracts/tokens/trc20/TRC20Freezable.sol";

/**
* @title Token contract for deploy
*/
contract Token is TRC20Detailed, TRC20Mintable, TRC20Freezable {}
```

Error on migration:
```
$ tronbox migrate
Using network 'development'.

Running migration: 3_deploy_token.js
  Deploying Token...
ERROR: Invalid bytecode provided
```

**Comment by pironmind** [comment]
All this contracts have import file, but files without imports has normal bytecode

**Comment by pironmind** [comment]
If I try pure compile have this errors
```
$ solcjs --bin ./contracts/tokens/trc20/Token.sol -o "build/contracts"
./contracts/tokens/trc20/Token.sol:3:1: ParserError: Source "./contracts/tokens/trc20/TRC20.sol" not found: File import callback not supported
import "../../../contracts/tokens/trc20/TRC20.sol";
^-------------------------------------------------^

./contracts/tokens/trc20/Token.sol:4:1: ParserError: Source "./contracts/tokens/trc20/TRC20Mintable.sol" not found: File import callback not supported
import "../../../contracts/tokens/trc20/TRC20Mintable.sol";
^---------------------------------------------------------^

./contracts/tokens/trc20/Token.sol:5:1: ParserError: Source "./contracts/tokens/trc20/TRC20Detailed.sol" not found: File import callback not supported
import "../../../contracts/tokens/trc20/TRC20Detailed.sol";
^---------------------------------------------------------^

./contracts/tokens/trc20/Token.sol:6:1: ParserError: Source "./contracts/tokens/trc20/TRC20Freezable.sol" not found: File import callback not supported
import "../../../contracts/tokens/trc20/TRC20Freezable.sol";
```

**Comment by pironmind** [comment]
Even if I add manually bytecode to json after deploy I have empty fields.
```
  "deployedBytecode": "0x",
  "sourceMap": "",
  "deployedSourceMap": "",
```

**Comment by pironmind** [comment]
let see this contract inculudes `trcToken, msg.tokenid, msg.tokenvalue`. Maybe problem with it?

**Comment by sullof** [comment]
It looks like it cannot find the imported contracts.

**Comment by pironmind** [comment]
> It looks like it cannot find the imported contracts. Are you sure that the path
> 
> ```
> import "../../../contract...
> ```
> 
> is the right one?

Anything ok with path. Bug with bytecode. Its  empty string.

**Comment by pironmind** [comment]
Source Code, check yourself:
https://github.com/pironmind/swap_trc10-to-20/tree/master

**Comment by sullof** [comment]
I am not working in Tron, but I think that when the bytecode is empty, it means that the compiler was unable to compile and, typically, this happens when in your code there is some unsupported peace of code. If some day I have time — and willing — I will try the code. In the meantime...

@shenyongri110 Are you still at Tron? If so, would you take a look?
