### ISSUE TITLE
tronbox init on Ubuntu has issue

### ISSUE THREAD

**Issue by leonboripgs** [tronprotocol/tronbox#86]
![image](https://user-images.githubusercontent.com/38007014/103227041-33a7c400-490c-11eb-86d2-83a104762560.png)

I can not initialize tronbox using tronbox cli.

**Comment by kjc233** [comment]
It's working here: https://github.com/Tronbox-boxes/bare-box/blob/master/tronbox.json and it wouldn't has negative effect for your project working.

It will be removed https://github.com/Tronbox-boxes/bare-box/blob/master/post-unpack.sh in your project.
