### ISSUE TITLE
Deploy with trc10 token address

### ISSUE THREAD

**Issue by partywave** [tronprotocol/tronbox#88]
A contract with a constructor like `constructor(trcToken _tokenId)` cannot be deployed in a migration with an integer value as such `await deployer.deploy(ContractArtifact, 1000001)`.

Error reported is `ERROR: invalid type (arg="type", value="trcToken", version=4.0.48)`. Please advise.

**Comment by llwslc** [comment]
Please try below this.
```solidity
constructor(uint256 _tokenId) public {
  trcToken _t = trcToken(_tokenId);
}
```

it's an upstream bug.
