### ISSUE TITLE
The java-tron package used by the docker-tron-quickstart project has not been updated

### ISSUE THREAD

**Issue by lylllll** [tronprotocol/tronbox#90]
when compiling the contract file of solidity 0.6 version：
env : Tronbox v2.7.18-beta.1
project:  tronbox unbox metacoin
![image](https://user-images.githubusercontent.com/73993249/105812006-68309d80-5fe8-11eb-9199-44cb81204999.png)

**Comment by llwslc** [comment]
Please use the stable version. Let us know if you still have problems.
