### ISSUE TITLE
Failed to compile solidity 0.6.0 special syntax

### ISSUE THREAD

**Issue by lylllll** [tronprotocol/tronbox#91]
version：Tronbox v2.7.18-beta.1
Project：tronbox unbox metacoin
ERROR :  tronbox compile --all  
Compile solidity 0.6.0 special syntax, use` tronbox test` command to get the following error！！
but   `tronbox compile --all`  is OK
![image](https://user-images.githubusercontent.com/73993249/105819136-c3678d80-5ff2-11eb-9f03-8043bdcae7cf.png)

**Comment by lylllll** [comment]
Now, call the fallback method has not been enabled

**Comment by llwslc** [comment]
Please use the stable version. Let us know if you still have problems.
