### ISSUE TITLE
How to set callValue or msg.value from migrations.js

### ISSUE THREAD

**Issue by guru260** [tronprotocol/tronbox#97]
I am learning solidity smart contract. I am using `tronbox` as my development framework. While deploying contract, I need to send some `trx` to contract address. So that It will be available in `msg.value`. For example this is my constructor function,
```
constructor() public payable {
    require(msg.value == 2 trx, "2 trx initial funding required");
}
```
How to send  `2 trx`, while deploying contract in migration file. For example this is my migration file,
```
var SimpleBank = artifacts.require("./Simple.sol");
var Migrations = artifacts.require("./Migrations.sol");

module.exports = function(deployer) {
  deployer.deploy(Simple);
  deployer.deploy(Migrations);
};
```

**Comment by llwslc** [comment]
Please add payable key to constructor's abi in /build/contracts/*.json

before
```json
{
  "inputs": [],
  "stateMutability": "payable",
  "type": "constructor"
},
```

after
```json
{
  "inputs": [],
  "stateMutability": "payable",
  "payable": true,
  "type": "constructor"
}
```

```js
deployer.deploy(Migrations, {callValue: 1});
```

It's an upstream bug.
