### ISSUE TITLE
solidity 0.6.2 or newer

### ISSUE THREAD

**Issue by smessmer** [tronprotocol/tronbox#99]
Are there plans on adding solidity 0.6.2 or newer compilers? Would that be hard to do?
Asking because openzeppelin requires 0.6.2 for most of its functionality, and 0.6.9 or newer for some.

**Comment by rubo** [comment]
Moreover, since the v4, OpenZeppelin switched to Solidity v0.8.0. OpenZeppelin is essential for smart contract development, and I'd love to use it for Tron development.

**Comment by llwslc** [comment]
Hi, We support 0.6.12 now.

**Comment by smessmer** [comment]
Thanks :)
